"""Add daily_likes_count and last_like_date to Client

Revision ID: 466bc2cdae30
Revises: 99dc3bdee233
Create Date: 2024-10-30 11:30:22.193987

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "466bc2cdae30"
down_revision: Union[str, None] = "99dc3bdee233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("daily_likes_count", sa.Integer(), nullable=True)
    )
    op.add_column("clients", sa.Column("last_like_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "last_like_date")
    op.drop_column("clients", "daily_likes_count")
    # ### end Alembic commands ###
