services:
  web:
    build: .
    container_name: fastapi_app
    command: >
        bash -c "
       
        
        alembic upgrade head &&
        
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
 
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env   
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1025:1025"   # SMTP порт для отправки почты
      - "1080:1080"   # Веб-интерфейс Mailcatcher
    networks:
      - app-network
networks:
  app-network:
    driver: bridge



volumes:
  postgres_data:
